### ISSUE TITLE
trackpad not working

### ISSUE THREAD

**Issue by vista136** [itsmeshibintmz/Acer-Nitro-5-AN515-54-Hackintosh#2]
please help my trackpad on acer nitro 5 is not working
how to fix it ?

**Comment by itsmeshibintmz** [comment]
Have u used all kexts provided? or have any changes been made? Also when using propertree, do an OC Snapshot and OC Clean snapshot with your EFI, some kext not needed for your system. do a oc snapshot and let me know the results.

**Comment by vista136** [comment]
i have use all kexts provided from this git, but when load the OC Snapshot
showing 2 warning

first. warning
   " Found OC Version 0.7.0 -> 0.7.2, Target Snapshot version 0.7.4 -> Current, Whould you like to snapshot for 0.7.0 -> 0.7.2 instead ? "
   
 second. waring
  " Duplicate CFBundleldentifiers

     Disable the following kexts with duplicate CFBundleldentifiers ?
     VoodooPS2Controller.kext/Contents/Plugins/VoodooInput.kext "


    Yes or No ?

**Comment by itsmeshibintmz** [comment]
For both warnings, click yes.

**Comment by cood1n** [comment]
Having the same issue, tried your solution but it didn't work.

**Comment by itsmeshibintmz** [comment]
> Having the same issue, tried your solution but it didn't work.

have you re-do the EFI with the Proper tree and disabled the kexts?

**Comment by cood1n** [comment]
Yes. Everything works fine now, but now my alt key is my command key and
whenever I hold the Windows Key it switches my keyboard to symbols. Any
idea on how to fix that?

**Comment by itsmeshibintmz** [comment]
> Yes. Everything works fine now, but now my alt key is my command key and whenever I hold the Windows Key it switches my keyboard to symbols. Any idea on how to fix that?

idk about that, I haven't faced any issues with the keyboard and Trackpad. You can try updating kexts. Maybe it'll help.

**Comment by cood1n** [comment]
Figured that out, it was another kext I had downloaded. I fixed all the problems I had with my trackpad by downloading the I2C SSDT from [this repo.](https://github.com/rinmichi/Nitro-5-AN515-54-Hackintosh/blob/master/OpenCore/EFI/OC/ACPI/SSDT-I2C-TPAD.aml)
