### ISSUE TITLE
Battery drain too fast

### ISSUE THREAD

**Issue by truongan2000pro** [itsmeshibintmz/Acer-Nitro-5-AN515-54-Hackintosh#3]
My battery when on usage is only about 1.5 hours and if lucky I got around 2 hours. How long can your laptop battery last?
My specs:
nitro 5 an515-54
i5 9300
gtx 1650
everything else work fine. Only the battery drain too fast make me worry. 
Thanks

**Comment by itsmeshibintmz** [comment]
I'm not sure. I use mine always plugged i . 1 time I remember used in battery mode and got better battery life than Windows, about 4.5-5 hrs.

**Comment by itsmeshibintmz** [comment]
@truongan2000pro Sorry, I don't have a proper answer for you right now. I've asked some friends who used my EFI and will get back to you in a few days.

**Comment by truongan2000pro** [comment]
> @truongan2000pro Sorry, I don't have a proper answer for you right now. I've asked some friends who used my EFI and will get back to you in a few days.

Oh thanks for helping me out

**Comment by truongan2000pro** [comment]
Hi, Have you know the answear yet? My battery is drain super fast :((

**Comment by itsmeshibintmz** [comment]
No idea, have you tried Monterey? It have any battery issue?

**Comment by truongan2000pro** [comment]
> No idea, have you tried Monterey? It have any battery issue?

I haven't tried it yet, I am scared Monterey is not compatible with my nitro 5

**Comment by itsmeshibintmz** [comment]
> > No idea, have you tried Monterey? It have any battery issue?
> 
> I haven't tried it yet, I am scared Monterey is not compatible with my nitro 5

if Big Sur is working for you, Monterey will also works. Give it a try!
